<?xml version="1.0" encoding="utf-8"?><Database Name="OPP" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=OPP;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="_18147171_QLNV.Properties.Settings" SettingsPropertyName="OPPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.qlnv1" Member="qlnv1s">
    <Type Name="qlnv1">
      <Column Name="emID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Dept" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>